### ISSUE TITLE
Est-ce que l'examen qu'on aura jeudi est un examen final ou bien un contrôle continu ?

### ISSUE THREAD

**Issue by MohammedSersouri** [prodageo/jdbc4uemf#10]
Est-ce que l'examen qu'on aura jeudi est un examen final ou bien un contrôle continu ?

**Comment by fbab** [comment]
Bonjour Mohammed,
Je vais me renseigner près de l'équipe pédagogique et je reviens vers toi.
Cordialement, FBA.

**Comment by fbab** [comment]
Bonjour Mohammed,

Il s'agit d'un examen final, comptant dans l'évaluation de la matière
"Interaction avec une base de données".
Cette évaluation sera notamment complétée par une note sur le projet avec
vos collègues de ROUEN.

Cordialement, FBA.
