### ISSUE TITLE
Question de cours 

### ISSUE THREAD

**Issue by Amineboukir** [prodageo/jdbc4uemf#11]
Bonjour Monsieur,
Es ce qu'on aura des questions de cours dans l'examen de Jeudi .
Merci ,

**Comment by fbab** [comment]
Bonjour Amine,

Je confirme qu'il y aura des questions de cours portant sur les supports en
ligne sur :
 - http://prodageo.insa-rouen.fr/uemf/saisonencours.CRENEAUX.html

Cordialement, FBA.
