### ISSUE TITLE
Est-ce que l'examen contiendra seulement des exercices similaires à celui que vous nous avez montré l'autre fois(EXBxx01)?

### ISSUE THREAD

**Issue by smashorpasstanger** [prodageo/jdbc4uemf#12]

**Comment by fbab** [comment]
Bonjour Imane,

En complément des réponses à #11 ou sur les [discussions](https://github.com/orgs/prodageo/teams/uemf2019p2sic/discussions/2), le programme de révision porte sur l'ensemble des séances.

Cordialement, FBA.
