### ISSUE TITLE
je ne comprends pas pourquoi dans la correction de l'ex EXB0052 le Numéros_De_Telephones est multivalué dans le 1er cas et monovalué dans le 2e ?

### ISSUE THREAD

**Issue by MohammedSersouri** [prodageo/jdbc4uemf#13]

**Comment by fbab** [comment]
Bonjour Mohammed,

C'est un choix de modélisation : 
- cas 2a : soit on choisit d'avoir un attribut par numéro de téléphone
- cas 2b : soit on choisit de créer un attribut intermédiaire (un attribut composite) qui contient lui-même deux attributs : un numéro de téléphone support et un numéro de téléphone standard.

Honnêtement, cela est très académique, et sans doute que dans le monde professionnel, on ne s'intéressera qu'au cas 2b.

Est-ce que cela répond à la question ?

Cordialement, FBA.

**Comment by MohammedSersouri** [comment]
Oui merci!
