### ISSUE TITLE
Est ce qu'on peut développer une application en utilisant seulement une base de données?

### ISSUE THREAD

**Issue by MohammedSersouri** [prodageo/jdbc4uemf#2]

**Comment by fbab** [comment]
Bonjour Mohammed,

Question vaste ! 

La base de données constitue un outil permettant de stocker les données au delà de l'exécution d'un programme (car les données du programme disparaissent de la RAM après arrêt d'un programme).

Je réponds à la question : est-ce que je peux faire une application informatique en utilisant uniquement une base de données ?

A priori, il faut toujours un complément par rapport à la base de données : ie un code Java, un code PHP qui sera exécuté par un runtime Java, un interpréteur PHP, ...
Même si on imagine que l'application propose aux utilisateurs de taper directement leurs requêtes en SQL pour obtenir les informations dont ils ont besoin (ou pour entrer de nouvelles données à l'aide de INSERT), il faudra en complément de la base de données, un client : 
 - comme Adminer que nous avons utilisé
 - ou psql, client en mode ligne de commande

Cordialement, FBA.
