### ISSUE TITLE
Question 😊

### ISSUE THREAD

**Issue by Amineboukir** [prodageo/jdbc4uemf#6]
J’ai pas bien compris la différence entre Partition type et power type

**Comment by fbab** [comment]
Bonjour Amine,

Le powertype est une classe (par exemple Marque ou Constructeur) qui contient des objets représentant des types d'une autre classe (par exemple Voiture).

La classe Voiture (partitioned type) contient les objets suivants :
 - F1 - la Ferrari de mon frère
 - F2 - la Ferrari de ma soeur
 - L1 - la Logan de mon voisin

La classe Constructeur (powertype) contient les objets suivants
 - Ferrari
 - Renault
Chaque objet de la classe Constructeur désigne un sous-ensemble des objets de la classe Voiture (le partition type)
 - Ferrari est un objet qui regroupe les objets F1 et F2 de la classe Voiture
 - Renault est un objet qui regroupe l'objet L1  de la classe Voiture

Cordialement, FBA.
