### ISSUE TITLE
Comment déterminer une pièce à conviction?

### ISSUE THREAD

**Issue by RADIyounes** [prodageo/jdbc4uemf#7]

**Comment by fbab** [comment]
Bonjour Younes,

Une pièce à conviction est un élément tangible (qu'on peut voir, toucher, ...) qui porte des éléments d'information échangés dans le domaine étudié et qui seront manipulé, à terme, par la solution informatique en développement.

Par exemple :
 - si je travaille sur un nouveau système de caisse automatique pour Marjane, le ticket de caisse d'un achat constitue une pièce à conviction ;
 - si je travaille sur une nouvelle version du système de gestion des salles à l'UEMF , une copie d'écran du système existant ADE,  constitue une pièce à conviction.

Cordialement, FBA.
