### ISSUE TITLE
Où peut-on trouver des ressources liés à SQL?

### ISSUE THREAD

**Issue by SoufianeMourchid** [prodageo/jdbc4uemf#8]

**Comment by fbab** [comment]
Bonjour Soufiane,

Il y a pléthores de ressources, en général, Google est ton ami ;)

Parmi les ressources en FR, on peut citer : 
 - https://sgbd.developpez.com/tutoriels/cours-complet-bases-de-donnees/?page=le-langage-sql2

Cordialement, FBA.
